# Generated by Django 5.1.2 on 2024-10-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.CharField(default='unknown', max_length=550),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expreience',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_category',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='max_salary',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='shifts',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(default='unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.CharField(default='01-01-2000', max_length=25),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(default='unknown', max_length=25),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(default='unknown', max_length=25),
        ),
    ]
