# Generated by Django 5.1.2 on 2024-10-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_candidate_country_candidate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
