# Generated by Django 5.1.2 on 2024-10-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_candidate_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='area',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
