# Generated by Django 5.1.2 on 2024-10-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_expreience_candidate_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.CharField(default='', max_length=550),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='shifts',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='website',
            field=models.CharField(default='', max_length=150),
        ),
    ]
