# Generated by Django 5.1.2 on 2024-10-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_company_description_alter_candidate_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=150),
        ),
    ]
