# Generated by Django 5.1.2 on 2024-10-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=100)),
                ('responsibilites', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('company_website', models.CharField(max_length=150)),
                ('company_email', models.CharField(max_length=50)),
                ('company_contact', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('exprience', models.IntegerField()),
            ],
        ),
    ]
