# Generated by Django 5.1.2 on 2024-11-06 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(default='', upload_to='app/img/jobpost'),
        ),
    ]
