# Generated by Django 5.1.2 on 2024-11-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_candidate_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='responsibilites',
            field=models.TextField(),
        ),
    ]
