# Generated by Django 5.1.2 on 2024-11-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_jobdetails_responsibilites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='exprience',
        ),
        migrations.RemoveField(
            model_name='jobdetails',
            name='responsibilites',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='experience',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='responsibilities',
            field=models.TextField(default=None),
        ),
    ]
