# Generated by Django 5.1.2 on 2024-11-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_jobdetails_exprience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='responsibilities',
            field=models.TextField(default='no specific responsibility is required '),
        ),
    ]
