# Generated by Django 5.1.2 on 2024-11-09 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_jobdetails_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
