# Generated by Django 5.1.2 on 2024-11-16 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_jobdetails_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='dead_line',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='shifts',
            field=models.CharField(default='not specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
