# Generated by Django 5.1.2 on 2024-11-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_jobdetails_dead_line_jobdetails_shifts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='shifts',
            field=models.CharField(default='full time ', max_length=20),
        ),
    ]
