# Generated by Django 5.1.2 on 2024-11-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_jobdetails_shifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='app/resumes')),
                ('experience', models.CharField(max_length=50)),
                ('coverletter', models.TextField()),
                ('email', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobdetails')),
            ],
        ),
    ]
