# Generated by Django 5.1.2 on 2024-11-19 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
