# Generated by Django 5.1.2 on 2024-11-20 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_queries_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
